import path from 'node:path';

export const normalize = (value) => value.normalize('NFD').replace(/\p{M}/gu, '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();

// Descriptions of the illustrated equipment, not specifications or prescriptions.
const groups = [
  [['prise electrique', 'prise et interrupteur'], 'Point de branchement ou de commande électrique, dont l’emplacement et la hauteur sont à adapter aux usages dans la pièce.'],
  [['pochette rangement accoudoirs canape'], 'Pochette fixée sur un accoudoir pour garder les petits objets du quotidien à portée de main depuis le canapé.'],
  [['machine a laver top'], 'Lave-linge à chargement par le dessus. Prévoir un accès dégagé au couvercle et aux commandes.'],
  [['machine a laver hublot'], 'Lave-linge à chargement frontal. L’accès au hublot et l’espace de manipulation du linge sont à prévoir.'],
  [['machine a laver en hauteur'], 'Installation du lave-linge sur un support surélevé, avec stabilité et accès aux raccordements à vérifier.'],
  [['four porte escamotable'], 'Four dont la porte se range sous la cavité après ouverture, pour dégager l’accès à l’intérieur.'],
  [['evier cuisine evide', 'lavabo pmr', 'lavabo suspendu', 'meuble vasque evide'], 'Point d’eau avec espace dégagé sous la cuve pour permettre une approche assise, selon la hauteur et les raccordements disponibles.'],
  [['plan w cuisine'], 'Plan de travail de cuisine dont la hauteur, la profondeur et les dégagements sont à adapter à la préparation des repas.'],
  [['ouverture de mur en remplacement porte', 'agrandir une porte', 'depose cloison'], 'Modification d’une ouverture ou d’une cloison pour dégager le passage. La faisabilité du chantier et la présence de réseaux doivent être vérifiées.'],
  [['cloison'], 'Cloison destinée à séparer ou à réorganiser les espaces intérieurs, en tenant compte des circulations et des équipements.'],
  [['porte coulissante', 'galandage'], 'Porte coulissant latéralement pour limiter le débattement dans la pièce. Prévoir le dégagement nécessaire au panneau et à sa poignée.'],
  [['porte automatique', 'porte automatisee'], 'Porte avec commande d’ouverture motorisée. Le déclenchement, la fermeture et les dispositifs de protection sont à adapter au passage.'],
  [['porte accordeon', 'porte pliante'], 'Porte à panneaux repliables pour réduire son débattement. Vérifier la largeur de passage une fois les panneaux ouverts.'],
  [['seuil plat', 'seuilencastre', 'porte seuil plat', 'seuil surbaisse'], 'Traitement du seuil visant à limiter le ressaut au passage de la porte, tout en tenant compte de l’étanchéité et du revêtement.'],
  [['porte battante', 'porte wc', 'porte d entree'], 'Porte battante dont la largeur utile, le sens d’ouverture et la poignée sont à adapter aux circulations et à l’espace disponible.'],
  [['sens de porte'], 'Modification du sens d’ouverture d’une porte pour améliorer le dégagement dans la pièce et l’accès aux équipements.'],
  [['poignee'], 'Poignée de porte dont la forme, la prise en main et l’emplacement sont à choisir en fonction des usages.'],
  [['porte de garage', 'porte de garage laterale'], 'Fermeture de garage dont l’ouverture et la commande sont à adapter à l’accès, au stationnement et au dégagement disponible.'],
  [['porte garage avec acces pieton'], 'Porte de garage intégrant un accès piéton distinct, pour entrer sans ouvrir l’ensemble de la fermeture.'],
  [['boule au volant'], 'Accessoire de préhension fixé au volant. Sa compatibilité avec le véhicule et les besoins de conduite doit être évaluée par un professionnel compétent.'],
  [['coussin triangulaire voiture'], 'Coussin de forme triangulaire destiné à ajuster la position d’assise dans le véhicule, sans gêner les commandes ni la ceinture.'],
  [['poele a granules'], 'Appareil de chauffage à granulés. Prévoir l’alimentation, l’évacuation des fumées, les dégagements et l’accès pour l’entretien.'],
  [['doublage isole des murs'], 'Doublage intérieur comprenant un isolant et un parement. Le choix du système tient compte des murs existants, de l’humidité et de l’espace disponible.'],
  [['vmc', 'vmc copie', 'extracteur air'], 'Équipement de ventilation destiné au renouvellement de l’air, à dimensionner selon le logement et les pièces concernées.'],
  [['main courante allee exterieure', 'maincourante exterieur', 'main courante exterieure sur poteaux', 'main courante exterieure sur pieds', 'main courante fixation sol', 'main courante', 'main courante escalier'], 'Main courante offrant un appui le long du cheminement ou de l’escalier. La continuité, la hauteur et la solidité des fixations sont à vérifier.'],
  [['portail motorise', 'portail electrique'], 'Portail motorisé pour commander l’accès extérieur. Prévoir une commande accessible et les dispositifs de protection adaptés.'],
  [['portillon'], 'Accès piéton extérieur dont la largeur, la manœuvre et le seuil sont à adapter au cheminement.'],
  [['extension'], 'Extension du logement pour créer ou réorganiser un espace. Le projet nécessite une étude de faisabilité et des démarches adaptées.'],
  [['rampe beton', 'rampe bois', 'rampe', 'pente', 'pente douce', 'pente douce beton', 'rampe d acces exterieure', 'rampe interieure'], 'Aménagement incliné pour franchir une différence de niveau. La pente, la longueur, les paliers et les appuis sont à étudier sur place.'],
  [['reperage contrastant', 'contremarche contrastee', 'contraste marche', 'lignes contrastantes'], 'Repères visuels contrastés pour rendre les changements de niveau ou les limites du cheminement plus visibles.'],
  [['escalier exterieur avec main courante'], 'Escalier extérieur accompagné d’une main courante. Examiner les marches, les paliers, le revêtement et la continuité de l’appui.'],
  [['cheminement antiderapant', 'revetement antiderapant', 'sol antiderapant'], 'Revêtement de cheminement à choisir selon l’usage, l’exposition à l’eau et les conditions d’entretien.'],
  [['marche largeur de pied', 'escalier exterieur marches profondes'], 'Marches avec une surface d’appui étendue. Les dimensions et les transitions avec les paliers sont à vérifier selon le passage.'],
  [['enrobe allee exterieure', 'cour goudron'], 'Revêtement extérieur en enrobé pour créer un cheminement continu. Prévoir les raccords, la pente et l’évacuation des eaux.'],
  [['marches antiderapantes exterieures', 'escalier bande antiderapante', 'bandelettes antiderapantes'], 'Bandes ou revêtements appliqués sur les zones d’appui pour améliorer l’adhérence, avec une pose et un entretien adaptés au support.'],
  [['flexstep'], 'Équipement de franchissement de niveau illustré sous le nom FlexStep. Le modèle et les conditions d’installation sont à confirmer auprès du fournisseur.'],
  [['toprostep'], 'Équipement d’assistance dans l’escalier illustré sous le nom ToproStep. La configuration et la compatibilité avec l’escalier sont à vérifier.'],
  [['garde corps escalier interieur'], 'Garde-corps en bordure d’escalier pour protéger le côté ouvert. La conception et les fixations doivent être adaptées à la configuration.'],
  [['applique led detecteur mouvement', 'lumiere automatique'], 'Éclairage déclenché automatiquement pour accompagner les déplacements. Régler le déclenchement et la durée selon la zone à éclairer.'],
  [['rampe 3 marche fixation mur perpendiculaire'], 'Appui de franchissement fixé sur un mur perpendiculaire aux marches. La position et la résistance de la fixation sont à vérifier sur place.'],
  [['escalier escamotable'], 'Escalier repliable pour accéder à un niveau supérieur. Son usage nécessite de vérifier la manœuvre, l’inclinaison et les appuis.'],
  [['siege monte escalier'], 'Siège motorisé se déplaçant sur un rail le long de l’escalier. Prévoir les transferts et les dégagements aux deux extrémités.'],
  [['cadre wc'], 'Cadre d’appui placé autour de la cuvette pour disposer de prises latérales. Vérifier la stabilité et l’espace de transfert.'],
  [['abattant automatique'], 'Abattant de toilettes à fonctionnement automatique. Les fonctions du modèle et ses besoins de raccordement sont à confirmer.'],
  [['cuvette surelevee', 'rehausseur wc'], 'Assise de toilettes rehaussée. La hauteur et la fixation sont à choisir selon la cuvette et les besoins de transfert.'],
  [['wc suspendu carrele', 'cuvette suspendue'], 'Cuvette suspendue sur bâti-support, avec une hauteur de pose à définir et un accès aux organes de maintenance à conserver.'],
  [['barre appui coudee droite cuvette', 'barre appui coudee gauche cuvette'], 'Barre d’appui coudée installée à côté des toilettes. Choisir son côté et son emplacement en fonction du transfert et du support de fixation.'],
  [['sanibroyeur'], 'WC ou dispositif équipé d’un broyeur pour l’évacuation. La compatibilité des raccordements et les contraintes d’entretien sont à vérifier.'],
  [['tringle escamotable', 'penderie escamotable'], 'Support de penderie abaissable pour rapprocher les vêtements. Prévoir le dégagement de manœuvre et vérifier la charge admissible du modèle.'],
  [['volets battants electriques', 'volet roulant electrique', 'volet roulant de velux solaire'], 'Volet motorisé pour commander l’ouverture et la fermeture. La commande et l’alimentation dépendent du modèle et de la fenêtre.'],
  [['eclairage'], 'Point d’éclairage pour la pièce ou le cheminement. Choisir son implantation en tenant compte des zones d’ombre et de l’éblouissement.'],
  [['tapis colle'], 'Tapis fixé au support pour limiter son déplacement. Vérifier l’adhérence, les bords et la compatibilité avec le passage.'],
  [['parquet dans une chambre', 'sol vinyle bois fonce'], 'Revêtement de sol intérieur dont les raccords, la résistance et l’entretien sont à adapter à la pièce et aux déplacements.'],
  [['decoupe de baignoire'], 'Création d’une ouverture dans la paroi d’une baignoire. Vérifier la compatibilité de la baignoire et les conditions d’accès et d’étanchéité.'],
  [['tapis pierre absorbante'], 'Tapis absorbant destiné à la sortie du point d’eau. Vérifier sa stabilité et la transition avec le sol environnant.'],
  [['fenetre dans douche'], 'Fenêtre située dans l’espace douche. Son ouverture, son accès et les raccords d’étanchéité sont à prendre en compte dans l’aménagement.'],
  [['television fixee au mur'], 'Téléviseur installé sur support mural. Choisir la hauteur et l’orientation selon la position de visionnage et vérifier la fixation.'],
  [['armoire de toilette avec miroir'], 'Rangement mural avec miroir au-dessus du point d’eau, à positionner en fonction de l’accès aux objets et de la visibilité.'],
  [['seche serviette'], 'Équipement de chauffage ou de séchage des serviettes, à installer selon le modèle et les contraintes de la salle de bain.'],
  [['baignoire'], 'Baignoire dont l’accès, les appuis et les possibilités d’assise sont à étudier dans l’aménagement de la salle de bain.'],
  [['joint douche'], 'Joint d’étanchéité aux raccords de la douche. Le support, la pose et l’état du joint doivent être vérifiés.'],
  [['ascenseur', 'plateforme elevatrice'], 'Équipement de transport vertical entre niveaux. La configuration, les accès et les conditions d’installation nécessitent une étude adaptée.'],
  [['tremis pour ascenseur'], 'Ouverture dans un plancher destinée au passage d’un ascenseur. Sa réalisation nécessite une vérification de la structure.'],
  [['fenetre battante', 'porte fenetre'], 'Menuiserie ouvrante dont la poignée, le débattement et le seuil sont à adapter à l’accès et à la manœuvre.'],
  [['fenetre velux motorisee'], 'Fenêtre de toit motorisée pour commander son ouverture à distance. Vérifier le modèle, l’alimentation et l’entretien.'],
  [['barre exterieure', 'barre relevable', 'barre d appui entree', 'barre de redressement au lit', 'barre d appui en angle', 'barre d appui', 'barre droite verticale', 'barre droite horizontale', 'barre d appui droite', 'barre en t', 'preconisation des barres d appui', 'barre d appui relevable', 'barre d appui coudee', 'barre sol plafond', 'barre d appui en l', 'barre de lit'], 'Appui destiné à accompagner les changements de position ou les déplacements. Sa forme, son orientation et ses fixations sont à adapter à l’usage et au support.'],
  [['sol pvc tarkett'], 'Revêtement de sol PVC illustré sous la marque Tarkett. La référence, les raccords et les conditions de pose restent à préciser.'],
  [['faience douche', 'paneau douche mural'], 'Revêtement mural pour l’espace douche, à poser avec un système d’étanchéité et des raccords adaptés au support.'],
  [['enfile bas de contention', 'enfile bas rolly', 'enfile chaussettes'], 'Aide à l’enfilage des bas ou des chaussettes. Choisir le modèle selon le vêtement et les possibilités de manipulation.'],
  [['fauteuil de douche grandes roues', 'chaise de douche a roulettes'], 'Assise de douche mobile. Vérifier l’accès à la douche, les transferts, l’immobilisation et l’usage prévu par le fabricant.'],
  [['planche de bain', 'banc de transfert baignoire'], 'Assise placée sur ou au-dessus de la baignoire pour organiser un transfert assis. Vérifier la compatibilité et la stabilité des appuis.'],
  [['tabouret douche', 'chaise de douche fixe', 'siede de douche avec accoudoirs et pieds large', 'siege de douche assise large', 'siege douche mural', 'siege'], 'Assise pour réaliser la toilette en position assise. La hauteur, les appuis et la stabilité sont à adapter à l’espace douche et au transfert.'],
  [['sandale brosse pied', 'brosse long manche'], 'Accessoire de toilette destiné à atteindre une zone difficile d’accès. La prise en main et l’usage en milieu humide sont à vérifier.'],
  [['chausse pied long manche', 'pince long manche chausse pied'], 'Aide à long manche pour l’habillage ou la manipulation d’objets, à choisir selon le geste et la prise en main recherchés.'],
  [['douche porte fixe battante', 'paroi fixe et volet mobile', 'porte de douche', 'porte douche coulissante', 'paroi fixe', 'paroi douche etroite', 'porte de douche ouverture horizontale'], 'Paroi ou porte de douche pour contenir les projections d’eau. Vérifier la largeur d’entrée, le débattement et l’accès aux commandes.'],
  [['mitigeur thermo automatique avec butee de temperature', 'mitigeur butee temperature', 'mitigeur thermo automatique'], 'Mitigeur de douche avec réglage de température. Les commandes et les fonctions du modèle doivent être vérifiées avant le choix.'],
  [['douche italienne', 'douche adaptee', 'douche adaptee 2', 'douche adaptee 3', 'receveur extra plat'], 'Aménagement de douche avec accès à étudier selon le ressaut, l’évacuation et les dégagements nécessaires à l’usage.'],
  [['paroi mi hauteur', 'porte mi hauteur'], 'Écran de douche de hauteur réduite, pour contenir les projections tout en laissant un accès par le dessus.'],
  [['robinet levier', 'mitigeur levier'], 'Robinet à commande par levier. La longueur, l’effort de manœuvre et l’emplacement sont à adapter à la prise en main.'],
  [['douche fermee par un muret'], 'Espace douche délimité par un muret. Prévoir l’entrée, les appuis éventuels et le traitement de l’étanchéité.'],
  [['douchette a main fine'], 'Douchette à main avec poignée fine. Vérifier la préhension, le flexible et la hauteur du support.'],
  [['rideau de douche'], 'Rideau pour limiter les projections d’eau tout en conservant une ouverture souple de l’espace douche.'],
  [['ciel de pluie'], 'Pommeau de douche supérieur. Prévoir sa position et la possibilité d’utiliser une douchette à main selon les besoins.'],
  [['robinet automatique'], 'Robinet à déclenchement automatique. Vérifier le mode de détection, le réglage de température et l’alimentation.'],
  [['double vasques adaptees', 'vasque suspendu miroir', 'lavabo pmr avec tiroirs lateraux', 'lavabo pmr avec armoire toilette', 'lavabo pmr avec poignees'], 'Ensemble de toilette aménagé autour d’une vasque. La hauteur, le dégagement des jambes, les rangements et le miroir sont à adapter à l’usage.'],
  [['miroir simple haut'], 'Miroir mural dont la hauteur et les dimensions sont à choisir pour permettre son utilisation depuis les positions habituelles.'],
  [['ouvre boite', 'ouvre bocal'], 'Accessoire d’ouverture pour les récipients alimentaires. Choisir le mécanisme selon la prise en main et les contenants utilisés.'],
  [['rail de trasnfert'], 'Rail destiné à un dispositif de transfert. Le parcours, les supports et l’équipement associé nécessitent une étude adaptée.'],
  [['couverts manche grossi'], 'Couverts avec manches élargis pour modifier la prise en main lors des repas. Le poids et la forme sont à choisir selon l’usage.'],
  [['assistance electrique tierce personne frm'], 'Dispositif d’assistance électrique à la poussée d’un fauteuil roulant manuel, dont la compatibilité avec le fauteuil doit être vérifiée.'],
  [['retire bas'], 'Accessoire destiné au retrait des bas, à choisir selon le vêtement et les possibilités de manipulation.'],
  [['fauteuil releveur'], 'Fauteuil avec mécanisme de relevage. Prévoir le dégagement autour du siège et une commande adaptée à l’utilisateur.'],
  [['montauban'], 'Chaise percée destinée à un usage de proximité. Vérifier la hauteur d’assise, les transferts et les modalités d’entretien.'],
  [['enfile bouton'], 'Accessoire d’habillage pour passer les boutons dans leurs boutonnières, à choisir selon la préhension et les vêtements.'],
  [['plateau sureleve'], 'Plateau surélevé pour rapprocher une surface de travail ou de repas. Vérifier sa stabilité et le dégagement sous le plateau.'],
  [['antiderapant'], 'Support antidérapant à placer sous les objets ou sur une surface adaptée pour limiter leur glissement.'],
];

const descriptions = new Map(groups.flatMap(([names, description]) => names.map(name => [normalize(name), description])));
const longNames = [
  ['meuble-bas-pour-evier-', 'Meuble bas pour évier', 'Meuble sous évier dont les rangements, les portes et le dégagement sont à adapter à l’usage de la cuisine.'],
  ['rideau-de-porte-isolant-', 'Rideau de porte isolant thermique', 'Rideau placé devant une porte pour limiter les échanges d’air, en conservant un passage et une manœuvre dégagés.'],
  ['rampe-de-seuil-', 'Rampe de seuil', 'Élément de franchissement d’un seuil. Vérifier sa hauteur, sa fixation et sa compatibilité avec la porte.'],
  ['garde-corps-acier-', 'Garde-corps acier PMR', 'Protection de rive en acier dont la hauteur, les ouvertures et les fixations sont à adapter à l’aménagement.'],
  ['marchepied-d-exterieur', 'Marchepied d’extérieur', 'Marchepied pour fractionner un changement de niveau. Vérifier la stabilité, l’appui du pied et l’exposition aux intempéries.'],
  ['Passerelle-pmr', 'Passerelle PMR', 'Passage surélevé pour relier deux zones, à étudier avec ses accès, ses appuis et ses protections latérales.'],
  ['beton-lisse-pour-terrasse', 'Béton lisse pour terrasse', 'Revêtement de terrasse en béton lisse. L’adhérence en présence d’eau et l’écoulement sont à vérifier.'],
  ['accoudoirs-toilettes-rabattables-', 'Accoudoirs toilettes rabattables Etac Supporter', 'Accoudoirs rabattables associés aux toilettes. Vérifier la compatibilité de fixation et le dégagement pour les transferts.'],
  ['carrelage-imitation-parquet-', 'Carrelage imitation parquet', 'Carrelage à aspect bois pour le sol intérieur, avec joints et finition à choisir selon la pièce et l’entretien.'],
  ['sol-anti-derapant-salle-de-bain', 'Sol antidérapant salle de bain', 'Revêtement pour le sol de la salle de bain, dont l’adhérence et les raccords sont à vérifier en conditions humides.'],
  ['barre-appui-maintien-inox-', 'Barre appui maintien inox', 'Barre d’appui en inox dont la position et les fixations sont à adapter à l’usage et au support.'],
  ['eponge-pour-dos-', 'Éponge pour dos Beauty', 'Éponge avec manche destinée à la toilette du dos. Vérifier la prise en main et l’entretien de l’accessoire.'],
  ['chaise-de-douche-ou-cuisine-', 'Chaise de douche ou cuisine assise haute', 'Assise haute dont l’usage en cuisine ou en douche dépend du modèle. Vérifier la stabilité, les appuis et les consignes du fabricant.'],
  ['pompe-de-relevage-douche-', 'Pompe de relevage douche BSF 250', 'Pompe destinée à relever les eaux de douche lorsque l’évacuation gravitaire n’est pas adaptée. Le dimensionnement et l’entretien sont à prévoir.'],
  ['cabines-de-douche-pour-personnes-', 'Cabine de douche avec receveur Braddan Access', 'Cabine de douche avec receveur. Vérifier le ressaut d’entrée, les dimensions utiles et la compatibilité des équipements.'],
  ['meuble-vasque-pmr-epure-80-cm-avec-miroir-led-elegance-et-caisson-', 'Meuble vasque PMR Épure avec miroir LED et caisson roulant', 'Ensemble vasque avec miroir et rangement mobile. Vérifier les dégagements, l’accès aux objets et la position du caisson.'],
  ['meuble-vasque-pmr-epure-80-cm-avec-miroir-led-', 'Meuble vasque PMR Épure avec miroir LED', 'Ensemble vasque avec miroir éclairé, dont la hauteur et le dégagement inférieur sont à adapter à l’utilisation.'],
];

export function photoMetadata(relativePath) {
  const stem = path.basename(relativePath, path.extname(relativePath)).normalize('NFC').trim();
  const override = longNames.find(([prefix]) => normalize(stem).startsWith(normalize(prefix)));
  const title = override?.[1] ?? (stem[0].toLocaleUpperCase('fr') + stem.slice(1)).replace(/_/g, ' ').replace(/\s+/g, ' ').replace(/^Siède /i, 'Siège ').replace(/trasnfert/i, 'transfert').replace(/^Trémis /i, 'Trémie ');
  const description = override?.[2] ?? descriptions.get(normalize(stem));
  if (!description) throw new Error(`Description missing: ${relativePath}`);
  const folder = relativePath.split('/')[0].normalize('NFC');
  const category = /^1_/.test(folder) ? 'Salle de bain' : /^2_/.test(folder) ? 'WC' : /^3_/.test(folder) ? "Barres d'appui" : /^(4_|5_ Ascenseur)/.test(folder) ? 'Escaliers & ascenseur' : /^6_/.test(folder) ? 'Accès extérieurs' : /^(5_ Portes|7_)/.test(folder) ? 'Ouvertures' : /^9_/.test(folder) ? 'Cuisine' : 'Equipements';
  return { title, description, category, tags: [category] };
}
